In [1]:
!pip install GEOparse

Collecting GEOparse
  Downloading GEOparse-2.0.4-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.0.2)
Requirement already satisfied: pandas>=0.17 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.2.2)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from GEOparse) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.17->GEOparse) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.21.0->GEOparse) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.17->GEOparse) (1.17.0)
Downloading GEOparse-2.0.4-py3-none-any.whl (29 kB)
Installing collected packages: GEOparse
Successfully installed GEOparse-2.0.4

In [2]:
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks/Personal/brain_disease_prediction/GEO/GEO toolkit')

In [3]:
from geo_processor import GEOProcessor
import pandas as pd
import numpy as np

In [4]:
file_path = "/content/drive/MyDrive/Colab Notebooks/Personal/brain_disease_prediction/GEO/Alzheimer/GSE5281/GSE5281_family.soft.gz"

gse = GEOProcessor(file_path)

In [5]:
gse.load_data()

30-Apr-2026 09:40:20 INFO GEOparse - Parsing /content/drive/MyDrive/Colab Notebooks/Personal/brain_disease_prediction/GEO/Alzheimer/GSE5281/GSE5281_family.soft.gz:
INFO:GEOparse:Parsing /content/drive/MyDrive/Colab Notebooks/Personal/brain_disease_prediction/GEO/Alzheimer/GSE5281/GSE5281_family.soft.gz:
30-Apr-2026 09:40:20 DEBUG GEOparse - DATABASE: GeoMiame
DEBUG:GEOparse:DATABASE: GeoMiame
30-Apr-2026 09:40:20 DEBUG GEOparse - SERIES: GSE5281
DEBUG:GEOparse:SERIES: GSE5281
30-Apr-2026 09:40:20 DEBUG GEOparse - PLATFORM: GPL570
DEBUG:GEOparse:PLATFORM: GPL570
/usr/local/lib/python3.12/dist-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
30-Apr-2026 09:40:27 DEBUG GEOparse - SAMPLE: GSM119615
DEBUG:GEOparse:SAMPLE: GSM119615
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119616
DEBUG:GEOparse:SAMPLE: GSM119616
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119617
DEBUG:GEOparse:SAMPLE: GSM119617
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119618
DEBUG:GEOparse:SAMPLE: GSM119618
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119619
DEBUG:GEOparse:SAMPLE: GSM119619
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119620
DEBUG:GEOparse:SAMPLE: GSM119620
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119621
DEBUG:GEOparse:SAMPLE: GSM119621
30-Apr-2026 09:40:28 DEBUG GEOparse - SAMPLE: GSM119622
DEBUG:GEOparse:SAMPLE: GSM119622
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119623
DEBUG:GEOparse:SAMPLE: GSM119623
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119624
DEBUG:GEOparse:SAMPLE: GSM119624
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119625
DEBUG:GEOparse:SAMPLE: GSM119625
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119626
DEBUG:GEOparse:SAMPLE: GSM119626
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119627
DEBUG:GEOparse:SAMPLE: GSM119627
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119628
DEBUG:GEOparse:SAMPLE: GSM119628
30-Apr-2026 09:40:29 DEBUG GEOparse - SAMPLE: GSM119629
DEBUG:GEOparse:SAMPLE: GSM119629
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119630
DEBUG:GEOparse:SAMPLE: GSM119630
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119631
DEBUG:GEOparse:SAMPLE: GSM119631
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119632
DEBUG:GEOparse:SAMPLE: GSM119632
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119633
DEBUG:GEOparse:SAMPLE: GSM119633
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119634
DEBUG:GEOparse:SAMPLE: GSM119634
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119635
DEBUG:GEOparse:SAMPLE: GSM119635
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119636
DEBUG:GEOparse:SAMPLE: GSM119636
30-Apr-2026 09:40:30 DEBUG GEOparse - SAMPLE: GSM119637
DEBUG:GEOparse:SAMPLE: GSM119637
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119638
DEBUG:GEOparse:SAMPLE: GSM119638
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119639
DEBUG:GEOparse:SAMPLE: GSM119639
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119640
DEBUG:GEOparse:SAMPLE: GSM119640
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119641
DEBUG:GEOparse:SAMPLE: GSM119641
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119642
DEBUG:GEOparse:SAMPLE: GSM119642
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119643
DEBUG:GEOparse:SAMPLE: GSM119643
30-Apr-2026 09:40:31 DEBUG GEOparse - SAMPLE: GSM119644
DEBUG:GEOparse:SAMPLE: GSM119644
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119645
DEBUG:GEOparse:SAMPLE: GSM119645
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119646
DEBUG:GEOparse:SAMPLE: GSM119646
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119647
DEBUG:GEOparse:SAMPLE: GSM119647
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119648
DEBUG:GEOparse:SAMPLE: GSM119648
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119649
DEBUG:GEOparse:SAMPLE: GSM119649
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119650
DEBUG:GEOparse:SAMPLE: GSM119650
30-Apr-2026 09:40:32 DEBUG GEOparse - SAMPLE: GSM119651
DEBUG:GEOparse:SAMPLE: GSM119651
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119652
DEBUG:GEOparse:SAMPLE: GSM119652
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119653
DEBUG:GEOparse:SAMPLE: GSM119653
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119654
DEBUG:GEOparse:SAMPLE: GSM119654
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119655
DEBUG:GEOparse:SAMPLE: GSM119655
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119656
DEBUG:GEOparse:SAMPLE: GSM119656
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119657
DEBUG:GEOparse:SAMPLE: GSM119657
30-Apr-2026 09:40:33 DEBUG GEOparse - SAMPLE: GSM119658
DEBUG:GEOparse:SAMPLE: GSM119658
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119659
DEBUG:GEOparse:SAMPLE: GSM119659
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119660
DEBUG:GEOparse:SAMPLE: GSM119660
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119661
DEBUG:GEOparse:SAMPLE: GSM119661
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119662
DEBUG:GEOparse:SAMPLE: GSM119662
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119663
DEBUG:GEOparse:SAMPLE: GSM119663
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119664
DEBUG:GEOparse:SAMPLE: GSM119664
30-Apr-2026 09:40:34 DEBUG GEOparse - SAMPLE: GSM119665
DEBUG:GEOparse:SAMPLE: GSM119665
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119666
DEBUG:GEOparse:SAMPLE: GSM119666
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119667
DEBUG:GEOparse:SAMPLE: GSM119667
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119668
DEBUG:GEOparse:SAMPLE: GSM119668
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119669
DEBUG:GEOparse:SAMPLE: GSM119669
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119670
DEBUG:GEOparse:SAMPLE: GSM119670
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119671
DEBUG:GEOparse:SAMPLE: GSM119671
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119672
DEBUG:GEOparse:SAMPLE: GSM119672
30-Apr-2026 09:40:35 DEBUG GEOparse - SAMPLE: GSM119673
DEBUG:GEOparse:SAMPLE: GSM119673
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119674
DEBUG:GEOparse:SAMPLE: GSM119674
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119675
DEBUG:GEOparse:SAMPLE: GSM119675
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119676
DEBUG:GEOparse:SAMPLE: GSM119676
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119677
DEBUG:GEOparse:SAMPLE: GSM119677
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119678
DEBUG:GEOparse:SAMPLE: GSM119678
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119679
DEBUG:GEOparse:SAMPLE: GSM119679
30-Apr-2026 09:40:36 DEBUG GEOparse - SAMPLE: GSM119680
DEBUG:GEOparse:SAMPLE: GSM119680
30-Apr-2026 09:40:37 DEBUG GEOparse - SAMPLE: GSM119681
DEBUG:GEOparse:SAMPLE: GSM119681
30-Apr-2026 09:40:37 DEBUG GEOparse - SAMPLE: GSM119682
DEBUG:GEOparse:SAMPLE: GSM119682
30-Apr-2026 09:40:37 DEBUG GEOparse - SAMPLE: GSM119683
DEBUG:GEOparse:SAMPLE: GSM119683
30-Apr-2026 09:40:37 DEBUG GEOparse - SAMPLE: GSM119684
DEBUG:GEOparse:SAMPLE: GSM119684
30-Apr-2026 09:40:37 DEBUG GEOparse - SAMPLE: GSM119685
DEBUG:GEOparse:SAMPLE: GSM119685
30-Apr-2026 09:40:38 DEBUG GEOparse - SAMPLE: GSM119686
DEBUG:GEOparse:SAMPLE: GSM119686
30-Apr-2026 09:40:38 DEBUG GEOparse - SAMPLE: GSM119687
DEBUG:GEOparse:SAMPLE: GSM119687
30-Apr-2026 09:40:38 DEBUG GEOparse - SAMPLE: GSM119688
DEBUG:GEOparse:SAMPLE: GSM119688
30-Apr-2026 09:40:38 DEBUG GEOparse - SAMPLE: GSM238763
DEBUG:GEOparse:SAMPLE: GSM238763
30-Apr-2026 09:40:38 DEBUG GEOparse - SAMPLE: GSM238790
DEBUG:GEOparse:SAMPLE: GSM238790
30-Apr-2026 09:40:39 DEBUG GEOparse - SAMPLE: GSM238791
DEBUG:GEOparse:SAMPLE: GSM238791
30-Apr-2026 09:40:39 DEBUG GEOparse - SAMPLE: GSM238792
DEBUG:GEOparse:SAMPLE: GSM238792
30-Apr-2026 09:40:39 DEBUG GEOparse - SAMPLE: GSM238793
DEBUG:GEOparse:SAMPLE: GSM238793
30-Apr-2026 09:40:39 DEBUG GEOparse - SAMPLE: GSM238794
DEBUG:GEOparse:SAMPLE: GSM238794
30-Apr-2026 09:40:40 DEBUG GEOparse - SAMPLE: GSM238795
DEBUG:GEOparse:SAMPLE: GSM238795
30-Apr-2026 09:40:40 DEBUG GEOparse - SAMPLE: GSM238796
DEBUG:GEOparse:SAMPLE: GSM238796
30-Apr-2026 09:40:40 DEBUG GEOparse - SAMPLE: GSM238797
DEBUG:GEOparse:SAMPLE: GSM238797
30-Apr-2026 09:40:40 DEBUG GEOparse - SAMPLE: GSM238798
DEBUG:GEOparse:SAMPLE: GSM238798
30-Apr-2026 09:40:41 DEBUG GEOparse - SAMPLE: GSM238799
DEBUG:GEOparse:SAMPLE: GSM238799
30-Apr-2026 09:40:41 DEBUG GEOparse - SAMPLE: GSM238800
DEBUG:GEOparse:SAMPLE: GSM238800
30-Apr-2026 09:40:41 DEBUG GEOparse - SAMPLE: GSM238801
DEBUG:GEOparse:SAMPLE: GSM238801
30-Apr-2026 09:40:41 DEBUG GEOparse - SAMPLE: GSM238802
DEBUG:GEOparse:SAMPLE: GSM238802
30-Apr-2026 09:40:41 DEBUG GEOparse - SAMPLE: GSM238803
DEBUG:GEOparse:SAMPLE: GSM238803
30-Apr-2026 09:40:42 DEBUG GEOparse - SAMPLE: GSM238804
DEBUG:GEOparse:SAMPLE: GSM238804
30-Apr-2026 09:40:42 DEBUG GEOparse - SAMPLE: GSM238805
DEBUG:GEOparse:SAMPLE: GSM238805
30-Apr-2026 09:40:42 DEBUG GEOparse - SAMPLE: GSM238806
DEBUG:GEOparse:SAMPLE: GSM238806
30-Apr-2026 09:40:42 DEBUG GEOparse - SAMPLE: GSM238807
DEBUG:GEOparse:SAMPLE: GSM238807
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238808
DEBUG:GEOparse:SAMPLE: GSM238808
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238809
DEBUG:GEOparse:SAMPLE: GSM238809
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238810
DEBUG:GEOparse:SAMPLE: GSM238810
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238811
DEBUG:GEOparse:SAMPLE: GSM238811
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238812
DEBUG:GEOparse:SAMPLE: GSM238812
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238813
DEBUG:GEOparse:SAMPLE: GSM238813
30-Apr-2026 09:40:43 DEBUG GEOparse - SAMPLE: GSM238815
DEBUG:GEOparse:SAMPLE: GSM238815
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238816
DEBUG:GEOparse:SAMPLE: GSM238816
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238817
DEBUG:GEOparse:SAMPLE: GSM238817
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238818
DEBUG:GEOparse:SAMPLE: GSM238818
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238819
DEBUG:GEOparse:SAMPLE: GSM238819
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238820
DEBUG:GEOparse:SAMPLE: GSM238820
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238821
DEBUG:GEOparse:SAMPLE: GSM238821
30-Apr-2026 09:40:44 DEBUG GEOparse - SAMPLE: GSM238822
DEBUG:GEOparse:SAMPLE: GSM238822
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238823
DEBUG:GEOparse:SAMPLE: GSM238823
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238824
DEBUG:GEOparse:SAMPLE: GSM238824
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238825
DEBUG:GEOparse:SAMPLE: GSM238825
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238826
DEBUG:GEOparse:SAMPLE: GSM238826
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238827
DEBUG:GEOparse:SAMPLE: GSM238827
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238834
DEBUG:GEOparse:SAMPLE: GSM238834
30-Apr-2026 09:40:45 DEBUG GEOparse - SAMPLE: GSM238835
DEBUG:GEOparse:SAMPLE: GSM238835
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238837
DEBUG:GEOparse:SAMPLE: GSM238837
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238838
DEBUG:GEOparse:SAMPLE: GSM238838
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238839
DEBUG:GEOparse:SAMPLE: GSM238839
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238840
DEBUG:GEOparse:SAMPLE: GSM238840
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238841
DEBUG:GEOparse:SAMPLE: GSM238841
30-Apr-2026 09:40:46 DEBUG GEOparse - SAMPLE: GSM238842
DEBUG:GEOparse:SAMPLE: GSM238842
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238843
DEBUG:GEOparse:SAMPLE: GSM238843
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238844
DEBUG:GEOparse:SAMPLE: GSM238844
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238845
DEBUG:GEOparse:SAMPLE: GSM238845
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238846
DEBUG:GEOparse:SAMPLE: GSM238846
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238847
DEBUG:GEOparse:SAMPLE: GSM238847
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238848
DEBUG:GEOparse:SAMPLE: GSM238848
30-Apr-2026 09:40:47 DEBUG GEOparse - SAMPLE: GSM238851
DEBUG:GEOparse:SAMPLE: GSM238851
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238854
DEBUG:GEOparse:SAMPLE: GSM238854
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238855
DEBUG:GEOparse:SAMPLE: GSM238855
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238856
DEBUG:GEOparse:SAMPLE: GSM238856
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238857
DEBUG:GEOparse:SAMPLE: GSM238857
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238858
DEBUG:GEOparse:SAMPLE: GSM238858
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238860
DEBUG:GEOparse:SAMPLE: GSM238860
30-Apr-2026 09:40:48 DEBUG GEOparse - SAMPLE: GSM238861
DEBUG:GEOparse:SAMPLE: GSM238861
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238862
DEBUG:GEOparse:SAMPLE: GSM238862
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238863
DEBUG:GEOparse:SAMPLE: GSM238863
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238864
DEBUG:GEOparse:SAMPLE: GSM238864
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238865
DEBUG:GEOparse:SAMPLE: GSM238865
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238867
DEBUG:GEOparse:SAMPLE: GSM238867
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238868
DEBUG:GEOparse:SAMPLE: GSM238868
30-Apr-2026 09:40:49 DEBUG GEOparse - SAMPLE: GSM238870
DEBUG:GEOparse:SAMPLE: GSM238870
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238871
DEBUG:GEOparse:SAMPLE: GSM238871
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238872
DEBUG:GEOparse:SAMPLE: GSM238872
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238873
DEBUG:GEOparse:SAMPLE: GSM238873
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238874
DEBUG:GEOparse:SAMPLE: GSM238874
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238875
DEBUG:GEOparse:SAMPLE: GSM238875
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238877
DEBUG:GEOparse:SAMPLE: GSM238877
30-Apr-2026 09:40:50 DEBUG GEOparse - SAMPLE: GSM238941
DEBUG:GEOparse:SAMPLE: GSM238941
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238942
DEBUG:GEOparse:SAMPLE: GSM238942
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238943
DEBUG:GEOparse:SAMPLE: GSM238943
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238944
DEBUG:GEOparse:SAMPLE: GSM238944
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238945
DEBUG:GEOparse:SAMPLE: GSM238945
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238946
DEBUG:GEOparse:SAMPLE: GSM238946
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238947
DEBUG:GEOparse:SAMPLE: GSM238947
30-Apr-2026 09:40:51 DEBUG GEOparse - SAMPLE: GSM238948
DEBUG:GEOparse:SAMPLE: GSM238948
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238949
DEBUG:GEOparse:SAMPLE: GSM238949
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238951
DEBUG:GEOparse:SAMPLE: GSM238951
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238952
DEBUG:GEOparse:SAMPLE: GSM238952
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238953
DEBUG:GEOparse:SAMPLE: GSM238953
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238955
DEBUG:GEOparse:SAMPLE: GSM238955
30-Apr-2026 09:40:52 DEBUG GEOparse - SAMPLE: GSM238963
DEBUG:GEOparse:SAMPLE: GSM238963

Loaded GSE5281

In [6]:
gse.show_info()

The GSE5281 dataset contains 161 patients
Title: Alzheimer's disease and the normal aged brain (steph-affy-human-433773)
Summary: Information about the genes that are preferentially expressed during the course of Alzheimer’s disease (AD) could improve our understanding of the molecular mechanisms involved in the pathogenesis of this common cause of cognitive impairment in older persons, provide new opportunities in the diagnosis, early detection, and tracking of this disorder, and provide novel targets for the discovery of interventions to treat and prevent this disorder. Information about the genes that are preferentially expressed in relationship to normal neurological aging could provide new information about the molecular mechanisms that are involved in normal age-related cognitive decline and a host of age-related neurological disorders, and they could provide novel targets for the discovery of interventions to mitigate some of these deleterious effects.

In [7]:
print(gse.get_patient_ids())

['GSM119615', 'GSM119616', 'GSM119617', 'GSM119618', 'GSM119619', 'GSM119620', 'GSM119621', 'GSM119622', 'GSM119623', 'GSM119624', 'GSM119625', 'GSM119626', 'GSM119627', 'GSM119628', 'GSM119629', 'GSM119630', 'GSM119631', 'GSM119632', 'GSM119633', 'GSM119634', 'GSM119635', 'GSM119636', 'GSM119637', 'GSM119638', 'GSM119639', 'GSM119640', 'GSM119641', 'GSM119642', 'GSM119643', 'GSM119644', 'GSM119645', 'GSM119646', 'GSM119647', 'GSM119648', 'GSM119649', 'GSM119650', 'GSM119651', 'GSM119652', 'GSM119653', 'GSM119654', 'GSM119655', 'GSM119656', 'GSM119657', 'GSM119658', 'GSM119659', 'GSM119660', 'GSM119661', 'GSM119662', 'GSM119663', 'GSM119664', 'GSM119665', 'GSM119666', 'GSM119667', 'GSM119668', 'GSM119669', 'GSM119670', 'GSM119671', 'GSM119672', 'GSM119673', 'GSM119674', 'GSM119675', 'GSM119676', 'GSM119677', 'GSM119678', 'GSM119679', 'GSM119680', 'GSM119681', 'GSM119682', 'GSM119683', 'GSM119684', 'GSM119685', 'GSM119686', 'GSM119687', 'GSM119688', 'GSM238763', 'GSM238790', 'GSM238791', 'GSM238792', 'GSM238793', 'GSM238794', 'GSM238795', 'GSM238796', 'GSM238797', 'GSM238798', 'GSM238799', 'GSM238800', 'GSM238801', 'GSM238802', 'GSM238803', 'GSM238804', 'GSM238805', 'GSM238806', 'GSM238807', 'GSM238808', 'GSM238809', 'GSM238810', 'GSM238811', 'GSM238812', 'GSM238813', 'GSM238815', 'GSM238816', 'GSM238817', 'GSM238818', 'GSM238819', 'GSM238820', 'GSM238821', 'GSM238822', 'GSM238823', 'GSM238824', 'GSM238825', 'GSM238826', 'GSM238827', 'GSM238834', 'GSM238835', 'GSM238837', 'GSM238838', 'GSM238839', 'GSM238840', 'GSM238841', 'GSM238842', 'GSM238843', 'GSM238844', 'GSM238845', 'GSM238846', 'GSM238847', 'GSM238848', 'GSM238851', 'GSM238854', 'GSM238855', 'GSM238856', 'GSM238857', 'GSM238858', 'GSM238860', 'GSM238861', 'GSM238862', 'GSM238863', 'GSM238864', 'GSM238865', 'GSM238867', 'GSM238868', 'GSM238870', 'GSM238871', 'GSM238872', 'GSM238873', 'GSM238874', 'GSM238875', 'GSM238877', 'GSM238941', 'GSM238942', 'GSM238943', 'GSM238944', 'GSM238945', 'GSM238946', 'GSM238947', 'GSM238948', 'GSM238949', 'GSM238951', 'GSM238952', 'GSM238953', 'GSM238955', 'GSM238963']

In [8]:
gse.show_patient_data("GSM119615")

Patient ID:
GSM119615

Patient gene data:
               ID_REF       VALUE ABS_CALL  DETECTION P-VALUE
0      AFFX-BioB-5_at  276.480650        P           0.000754
1      AFFX-BioB-M_at  391.856960        P           0.000169
2      AFFX-BioB-3_at  269.120820        P           0.000095
3      AFFX-BioC-5_at  852.272400        P           0.000095
4      AFFX-BioC-3_at  821.932430        P           0.000044
...               ...         ...      ...                ...
54670      1570644_at   45.333084        A           0.274170
54671      1570645_at    8.507533        A           0.239258
54672      1570650_at   40.956710        A           0.398926
54673      1570651_at   31.751217        A           0.633789
54674      1570653_at   13.508081        A           0.725830

[54675 rows x 4 columns]

Patient metadata:
{'title': ['EC control 1'], 'geo_accession': ['GSM119615'], 'status': ['Public on Jul 10 2006'], 'submission_date': ['Jul 10 2006'], 'last_update_date': ['Jun 26 2019'], 'type': ['RNA'], 'channel_count': ['1'], 'source_name_ch1': ['brain, Entorhinal Cortex'], 'organism_ch1': ['Homo sapiens'], 'taxid_ch1': ['9606'], 'characteristics_ch1': ['Sample Amount: 10 ug', 'Bio-Source Name: EC control 1', 'Organism: Human', 'Organ/Tissue Type: brain', 'Organ Region: Entorhinal Cortex', 'Cell Type: layer III neurons', 'Ethnicity: Caucasian', 'Developmental Stage: Adult', 'Disease State: normal', 'Sex: male', 'Genetic Variation: None', 'Age: 63 years'], 'molecule_ch1': ['total RNA'], 'description': ['arrayconsortium.tgen.org::biosample.433887', 'AD control'], 'platform_id': ['GPL570'], 'contact_name': ['Winnie,,Liang'], 'contact_email': ['wliang@tgen.org'], 'contact_institute': ['Translational Genomics'], 'contact_address': ['445 N. Fifth Street'], 'contact_city': ['Phoenix'], 'contact_state': ['AZ'], 'contact_zip/postal_code': ['85012'], 'contact_country': ['USA'], 'supplementary_file': ['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM119nnn/GSM119615/suppl/GSM119615.CEL.gz'], 'relation': ['Reanalyzed by: GSE64985', 'Reanalyzed by: GSE119087', 'Reanalyzed by: GSE133349'], 'series_id': ['GSE5281'], 'data_row_count': ['54675']}

In [9]:
gse.show_patient_metadata("GSM119615")

title: ['EC control 1']
geo_accession: ['GSM119615']
status: ['Public on Jul 10 2006']
submission_date: ['Jul 10 2006']
last_update_date: ['Jun 26 2019']
type: ['RNA']
channel_count: ['1']
source_name_ch1: ['brain, Entorhinal Cortex']
organism_ch1: ['Homo sapiens']
taxid_ch1: ['9606']
characteristics_ch1: ['Sample Amount: 10 ug', 'Bio-Source Name: EC control 1', 'Organism: Human', 'Organ/Tissue Type: brain', 'Organ Region: Entorhinal Cortex', 'Cell Type: layer III neurons', 'Ethnicity: Caucasian', 'Developmental Stage: Adult', 'Disease State: normal', 'Sex: male', 'Genetic Variation: None', 'Age: 63 years']
molecule_ch1: ['total RNA']
description: ['arrayconsortium.tgen.org::biosample.433887', 'AD control']
platform_id: ['GPL570']
contact_name: ['Winnie,,Liang']
contact_email: ['wliang@tgen.org']
contact_institute: ['Translational Genomics']
contact_address: ['445 N. Fifth Street']
contact_city: ['Phoenix']
contact_state: ['AZ']
contact_zip/postal_code: ['85012']
contact_country: ['USA']
supplementary_file: ['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM119nnn/GSM119615/suppl/GSM119615.CEL.gz']
relation: ['Reanalyzed by: GSE64985', 'Reanalyzed by: GSE119087', 'Reanalyzed by: GSE133349']
series_id: ['GSE5281']
data_row_count: ['54675']

In [10]:
print(gse.get_table_columns())

['ID_REF', 'VALUE', 'ABS_CALL', 'DETECTION P-VALUE']

In [12]:
dfs = gse.build_data_frames()

In [17]:
dfs["value"]

,GSM119615,GSM119616,GSM119617,GSM119618,GSM119619,GSM119620,GSM119621,GSM119622,GSM119623,GSM119624,...,GSM238945,GSM238946,GSM238947,GSM238948,GSM238949,GSM238951,GSM238952,GSM238953,GSM238955,GSM238963
ID_REF,,,,,,,,,,,,,,,,,,,,,
AFFX-BioB-5_at,276.480650,173.886460,340.415950,462.013850,969.227840,315.652620,795.894400,418.467130,256.375120,291.719900,...,972.15500,2605.9800,1875.17000,1782.7600,1814.72000,543.33100,1170.2200,589.42400,2318.74000,2210.29000
AFFX-BioB-M_at,391.856960,248.449940,395.968800,605.429000,1353.379600,499.425750,952.377800,457.690400,325.488200,377.045500,...,1736.17000,4610.9700,3108.58000,3589.8400,3345.61000,884.61100,1943.2000,891.00300,3872.99000,3533.48000
AFFX-BioB-3_at,269.120820,129.086730,256.594270,268.400400,846.799600,217.215410,606.752700,336.621220,187.439000,223.546720,...,970.95000,3009.0400,1872.00000,2237.9200,2081.44000,549.71800,1222.4600,560.00800,2434.82000,2363.41000
AFFX-BioC-5_at,852.272400,581.811700,1096.706300,1461.096700,2789.578100,1115.102300,2507.301800,1311.187600,927.735200,995.292660,...,2425.16000,6232.2000,4171.50000,5293.1200,4604.43000,1805.26000,4011.1600,1691.09000,5098.79000,6520.74000
AFFX-BioC-3_at,821.932430,849.975160,1438.471000,1698.329700,3443.694600,1456.831900,3133.805700,1812.012500,1187.363500,1282.108600,...,2543.77000,6462.5300,4657.46000,5592.9400,5078.74000,2018.44000,4813.1900,2005.70000,6109.55000,7303.75000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1570644_at,45.333084,39.368587,91.836380,18.226810,90.429170,14.700465,6.759470,6.348751,8.608525,2.863409,...,8.93185,10.4283,96.76590,96.5165,35.10410,14.30280,31.5172,16.90710,5.95791,10.58140
1570645_at,8.507533,2.387396,11.159609,8.078927,2.897786,20.314146,82.530310,27.289642,30.251290,5.919386,...,7.90022,32.4251,56.43200,78.6636,11.32170,15.31220,28.1371,11.84790,22.03070,91.65880
1570650_at,40.956710,40.124730,80.728134,76.397285,51.699700,24.892952,26.549267,10.330388,11.123620,13.153028,...,8.48468,8.4333,3.87097,110.3420,5.21763,22.15090,7.9910,1.08616,10.32990,8.40852
1570651_at,31.751217,32.498660,92.726260,94.155716,64.194610,23.942245,67.941970,68.469980,71.703470,3.288359,...,59.88610,141.4870,35.38950,214.6390,127.49700,25.37770,61.1111,20.11780,240.92600,47.59100
1570653_at,13.508081,20.270626,77.864815,7.936954,58.996044,70.317215,26.915274,35.345840,33.881390,11.174695,...,38.67140,41.1729,3.03753,99.7701,2.50209,1.61942,11.1665,9.81287,16.00960,11.47000

In [22]:
gse.get_patient_labels("GSM119615")

Patient: GSM119615
Sample Amount: 10 ug
Bio-Source Name: EC control 1
Organism: Human
Organ/Tissue Type: brain
Organ Region: Entorhinal Cortex
Cell Type: layer III neurons
Ethnicity: Caucasian
Developmental Stage: Adult
Disease State: normal
Sex: male
Genetic Variation: None
Age: 63 years

('GSM119615',
 ['Sample Amount: 10 ug',
  'Bio-Source Name: EC control 1',
  'Organism: Human',
  'Organ/Tissue Type: brain',
  'Organ Region: Entorhinal Cortex',
  'Cell Type: layer III neurons',
  'Ethnicity: Caucasian',
  'Developmental Stage: Adult',
  'Disease State: normal',
  'Sex: male',
  'Genetic Variation: None',
  'Age: 63 years'])

In [27]:
gse.build_gse_metadata()

,patient_id,sample amount,bio-source name,organism,organ/tissue type,organ region,cell type,ethnicity,developmental stage,disease state,sex,genetic variation,age
0,GSM119615,10 ug,EC control 1,Human,brain,Entorhinal Cortex,layer III neurons,Caucasian,Adult,normal,male,None,63 years
1,GSM119616,10 ug,EC control 2,Human,brain,Entorhinal Cortex,layer III neurons,Caucasian,Adult,normal,male,None,85 years
2,GSM119617,10 ug,EC control 3,Human,brain,Entorhinal Cortex,layer III neurons,Caucasian,Adult,normal,male,None,80 years
3,GSM119618,10 ug,EC control 4,Human,brain,Entorhinal Cortex,layer III neurons,Caucasian,Adult,normal,male,None,80 years
4,GSM119619,10 ug,EC control 5,Human,brain,Entorhinal Cortex,layer III neurons,Caucasian,Adult,normal,female,None,102 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,GSM238951,10 ng,VCX_affected_15,Human,brain,Primary Visual Cortex,pyramidal neuron,unknown,Adult,Alzheimer's Disease,female,None,82 years
157,GSM238952,10 ng,VCX_affected_16,Human,brain,Primary Visual Cortex,pyramidal neuron,unknown,Adult,Alzheimer's Disease,male,None,88 years
158,GSM238953,10 ng,VCX_affected_17,Human,brain,Primary Visual Cortex,pyramidal neuron,unknown,Adult,Alzheimer's Disease,male,None,74 years
159,GSM238955,10 ng,VCX_affected_18,Human,brain,Primary Visual Cortex,layer III neurons,Caucasian,Adult,Alzheimer's Disease,male,None,72 years
160,GSM238963,10 ng,VCX_affected_19,Human,brain,Primary Visual Cortex,layer III neurons,Caucasian,Adult,Alzheimer's Disease,female,None,80 years